### ISSUE TITLE
Model with UUID association gets re-created when other fields are updated

### ISSUE THREAD

**Issue by codecat** [go-gorm/gorm#6375] opened 2023-06-04 17:25 UTC
## GORM Playground Link
https://github.com/go-gorm/playground/pull/607

## Description
I am trying to use UUID's as primary keys, and find that while updating the model that associates with another model, a brand new model gets created, even when the ID field is untouched.

This can easily be observed in the playground PR: A new Company is created, then a User is created with the Company's UUID. Then, we get the User row w/ the Company field preloaded, and try to update the name. Now a new Company is also created.

**Comment by black-06** [comment] 2023-06-05 07:44
Duplicate of #6324 and #6356

**Closed by black-06** 2023-06-05 07:44 UTC
Labels: type:with reproduction steps
