### ISSUE TITLE
Sqlite Create Fails With Empty String and Default NULL

### ISSUE THREAD

**Issue by samc1213** [go-gorm/gorm#6335] opened 2023-05-19 17:13 UTC
## GORM Playground Link

https://github.com/go-gorm/playground/pull/598

## Description

See playground for example - with sqlite, if you set a string field to be `gorm:"default:null"`, and its value is empty string, when you go to insert multiple entities, gorm tries to use the `DEFAULT` keyword (I believe it's from [here](https://github.com/go-gorm/sqlite/blob/0d652e16cdf4ab215f20d973cb89c70729e18a84/sqlite.go#L129-L130)), which is invalid in sqlite, causing an error. Is there any way to fix this aside from inserting each entity one at a time?

**Comment by black-06** [comment] 2023-05-22 05:18
It's related to https://github.com/go-gorm/sqlite/blob/0d652e16cdf4ab215f20d973cb89c70729e18a84/sqlite.go#L124-131

```go
func (dialector Dialector) DefaultValueOf(field *schema.Field) clause.Expression {
	if field.AutoIncrement {
		return clause.Expr{SQL: "NULL"}
	}

	// doesn't work, will raise error
	return clause.Expr{SQL: "DEFAULT"}
}
```

Is this a bug ? @a631807682

**Comment by black-06** [comment] 2023-05-22 10:09
Sry, I was wrong, this is not a bug.
There is no way to insert both the specified value and the default value in SQLite.

Maybe you can assign the default value to the field in the hook, e.g.
```go
type NullableStringType struct {
	Value string `gorm:"default:'abcd'"`
}

func (p *NullableStringType) BeforeCreate(tx *gorm.DB) (err error) {
	if p.Value == "" {
		p.Value = 'abcd'
	}
}
```

**Comment by a631807682** [comment] 2023-05-22 15:23
Perhaps we should clearly point out that sqlite does not support it, and the meaning of the comments here is not clear enough.
Anyway, sqlite doesn't support that, we currently don't have label management for `won't fix`, so I close it.

**Closed by a631807682** 2023-05-22 15:23 UTC
Labels: type:with reproduction steps

**Comment by samc1213** [comment] 2023-05-22 17:36
Thank you both for taking a look.

For anyone looking at this issue in the future:

The simplest workaround is to use individual insert statements. I.e., instead of 

```go
value := NullableStringType{Value: "jinzhu"}
value2 := NullableStringType{}
values := []NullableStringType{value, value2}

tx := DB.Create(&values)
```

do this:

```go
value := NullableStringType{Value: "jinzhu"}
value2 := NullableStringType{}

tx := DB.Create(&value)
tx := DB.Create(&value2)
```

I agree that this is hard to fix given SQLite's lack of support for `DEFAULT` keyword.

**Comment by bkmeneguello** [comment] 2024-05-21 12:56
Is it possible to disable batch if the database doesn't support it? Maybe during the Create function call check if the schema have default values and if the database supports and "automagically" consider the batch size as "1"?

**Comment by Baldur404** [comment] 2025-01-02 16:10
> Is it possible to disable batch if the database doesn't support it? Maybe during the Create function call check if the schema have default values and if the database supports and "automagically" consider the batch size as "1"?

yes ,it’s counter-intuitive,if a developer does not check doc or this issue,they will write unpredictable code,In my opinion fixing it to support batch insertion of default values is not difficult,the key point is whether to implement it or not. Grom is a framework,the framework should encapsulation code to give developer a clear and easy way to use it
-personal opinion
